/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-22 08:13:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.Board;
import java.util.ArrayList;
import board.model.vo.BoardPageInfo;
import member.model.vo.Member;

public final class BoardMainTotal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1566448879317L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1566450389929L));
    _jspx_dependants.put("/views/Board/BoardListNav.jsp", Long.valueOf(1566346953163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("board.model.vo.BoardPageInfo");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	ArrayList<Board> tlist = (ArrayList<Board>)request.getAttribute("tlist");
	
	BoardPageInfo bpi = (BoardPageInfo)request.getAttribute("bpi");
	
	int boardCount = bpi.getBoardCount();
	int currentPage = bpi.getCurrentPage();
	int maxPage = bpi.getMaxPage();
	int startPage = bpi.getStartPage();
	int endPage = bpi.getEndPage();
	int limit = bpi.getLimit();
	int pagingBarSize = bpi.getPageingBarSize();
	
	/* request.setAttribute("tlist", tlist);
	request.setAttribute("bpi", bpi); */

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BoardMainTotal</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("\t       #Boardtotal{\r\n");
      out.write("\t           /* \twidth: 100%; */\r\n");
      out.write("\t         \theight: auto;\r\n");
      out.write("\t           \tmargin: auto;\r\n");
      out.write("\t          \tpadding: 0;\r\n");
      out.write("\t          \tcolor: black;\r\n");
      out.write("\t       \t}\r\n");
      out.write("\t       \t#header{\r\n");
      out.write("\t        \twidth: 100%;\r\n");
      out.write("\t        \t/* height : 80px; */\r\n");
      out.write("\t        \tmargin : 0;\r\n");
      out.write("\t        \tpadding : 0;\r\n");
      out.write("\t        \tclear : both;\r\n");
      out.write("\t        }\r\n");
      out.write("\t     /*  body{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: auto;\r\n");
      out.write("\t        \tmargin: auto;\r\n");
      out.write("\t        } */\r\n");
      out.write("\t       /* article, section,nav{\r\n");
      out.write("\t          border: 1px solid black; */\r\n");
      out.write("\t            /* margin: 0;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t            width: 1080px; */\r\n");
      out.write("\t        }\r\n");
      out.write("\t        #bnav{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 150px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t            clear : both;\r\n");
      out.write("\t            \r\n");
      out.write("\t        }\r\n");
      out.write("\t        #ad{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 200px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t            \r\n");
      out.write("\t        }\r\n");
      out.write("\t        #blist{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 600px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t        }\r\n");
      out.write("\t       /*  #btn{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 100px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding-top: 5px;\r\n");
      out.write("\t            \r\n");
      out.write("\t        }\r\n");
      out.write("\t        #page{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 100px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t        } */\r\n");
      out.write("\t        /* -----틀잡기----- */\r\n");
      out.write("\t       \r\n");
      out.write("\t       \r\n");
      out.write("\t       #ad-2{\r\n");
      out.write("\t            width: 1000px;\r\n");
      out.write("\t            height: 80%;\r\n");
      out.write("\t           /*  margin-top: 20px; */\r\n");
      out.write("\t            margin-left: 38px;\r\n");
      out.write("\t            background-color:#4F90CC;\r\n");
      out.write("\t            color : white;\r\n");
      out.write("\t            font-size: 50px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tpadding-top:40px;\r\n");
      out.write("\t            \r\n");
      out.write("\t        }\r\n");
      out.write("\t       /*  #menu{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 100px;\r\n");
      out.write("\t            padding-top: 15px;\r\n");
      out.write("\t            margin : auto;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        #page{\r\n");
      out.write("\t            padding-left: 450px; \r\n");
      out.write("\t        }  */\r\n");
      out.write("\t        \r\n");
      out.write("\t        #boardlist{\r\n");
      out.write("\t            width: 1080px;\r\n");
      out.write("\t            height: 550px;\r\n");
      out.write("\t            margin: auto;\r\n");
      out.write("\t            padding: 0;\r\n");
      out.write("\t            color: black;\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\t#boardbtn{\r\n");
      out.write("\t\t            width: 1080px;\r\n");
      out.write("\t\t            height: 80px;\r\n");
      out.write("\t\t            margin: auto;\r\n");
      out.write("\t\t            padding-top: 10px;\r\n");
      out.write("\t\t            color: black;\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t   \t#boardpage{\r\n");
      out.write("\t\t            width: 1080px;\r\n");
      out.write("\t\t            height: 100px;\r\n");
      out.write("\t\t            margin: auto;\r\n");
      out.write("\t\t            padding: 0;\r\n");
      out.write("\t\t            padding-left: 360px;\r\n");
      out.write("\t\t            color: black;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    #searchselect{\r\n");
      out.write("\t\t    \tmargin:0;\r\n");
      out.write("\t\t    \tpadding: 0;\r\n");
      out.write("\t\t    \tfloat:left;\r\n");
      out.write("\t\t    \tdisplay: block;\r\n");
      out.write("\t\t    \tpadding-top: 5px;\r\n");
      out.write("\t\t    \tpadding-bottom: 8px;\r\n");
      out.write("\t\t    \tmargin-left:10px;\r\n");
      out.write("\t\t    \tcolor: black;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    .form-inline{\r\n");
      out.write("\t\t           display: block;\r\n");
      out.write("\t\t           float: left;\r\n");
      out.write("\t\t           margin-right: 10px;\r\n");
      out.write("\t\t           margin-top:0;\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t    #boardlisttable{\r\n");
      out.write("\t\t    \ttext-align: center;\r\n");
      out.write("\t\t    \tcolor: black;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    \r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"Boardtotal\">\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t\t");
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>MENUBAR</title>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #footer-1 {\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("    \theight: 80%;\r\n");
      out.write("    \tfloat: left;\r\n");
      out.write("    \tpadding-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer-1 li {\r\n");
      out.write("    \tdisplay: inline;\r\n");
      out.write("    \tfont-weight: bold;\r\n");
      out.write("    \tfont-size: 17px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer-1 a {\r\n");
      out.write("    \ttext-decoration: none !important;\r\n");
      out.write("    \tcolor: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer-2 {\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("        height: 20%;\r\n");
      out.write("    \tfloat: left;\r\n");
      out.write("    \tfont-size: 15px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div id=\"footer-1\">\r\n");
      out.write("\t\t\t<div id=\"footer-nav\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li> |\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개인정보 취급방침</a></li> |\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개발자</a></li>\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer-2\">\r\n");
      out.write("\t\t\t<p>Copyright © 2019 HSH All Right Reserved</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("<!-- jQuery CDN -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Google WebIcon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n");
      out.write("<!-- Google WebFont -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<!-- Bootstrap 4.3.1 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n");
      out.write("<!-- Bootstrap select -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css\" />\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js\"></script> -->\n");
      out.write("\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- SweetAlert2 -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@8\"></script>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("    * {\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        margin: 0px;\n");
      out.write("        padding: 0px;\n");
      out.write("        text-decoration: none;\n");
      out.write("        user-select: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("        /* font-family: 'Noto Sans KR', sans-serif; */\n");
      out.write("        font-size: 14px !important;\n");
      out.write("        /* min-width: 1200px !important; */\n");
      out.write("        width:100%;\n");
      out.write("        margin: auto;\n");
      out.write("        min-height: 100%;\n");
      out.write("        height: auto;\n");
      out.write("        position: relative;\n");
      out.write("        margin-bottom: 180px !important;\n");
      out.write("        padding-bottom: 80px !important;\n");
      out.write("    }\n");
      out.write("/*     .clear {\n");
      out.write("    \tmargin-bottom: 80px;\n");
      out.write("    } */\n");
      out.write("    footer {\n");
      out.write("        background-color: #8ba7c9;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 180px;\n");
      out.write("        z-index: 1000;\n");
      out.write("        bottom: -180px;\n");
      out.write("        /* margin: auto; */\n");
      out.write("        color: white;\n");
      out.write("    \ttext-align: center;\n");
      out.write("        position: absolute;\n");
      out.write("    }\n");
      out.write("    header {\n");
      out.write("        background-color: #00264B;\n");
      out.write("        width: 100%;\n");
      out.write("        z-index: 2;\n");
      out.write("    }\n");
      out.write("    #logo{\n");
      out.write("        width:180px;\n");
      out.write("        color: #fff;\n");
      out.write("        font-weight: 900;\n");
      out.write("        font-size: 40px;\n");
      out.write("        text-align: center;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #menubarNav {\n");
      out.write("        float: left;\n");
      out.write("        /* height: 80px; */\n");
      out.write("    }\n");
      out.write("/*     #blank {\n");
      out.write("        width: 28%;\n");
      out.write("        float: left;\n");
      out.write("    } */\n");
      out.write("    #login {\n");
      out.write("        width: 7%;\n");
      out.write("        float: right;\n");
      out.write("    }\n");
      out.write("    #login i {\n");
      out.write("        text-align: center;\n");
      out.write("        font-size: 40px;\n");
      out.write("        color: white;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #login-menu{\n");
      out.write("        width: 230px;\n");
      out.write("        height: 270px;\n");
      out.write("        background-color: white;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        float: right;\n");
      out.write("        position: absolute;\n");
      out.write("        top: 50px;\n");
      out.write("        text-align: center;\n");
      out.write("        right: 0px;\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #mypageMenu{\n");
      out.write("    \twidth: 200px;\n");
      out.write("        height: 230px;\n");
      out.write("        background-color: white;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        float: right;\n");
      out.write("        position: absolute;\n");
      out.write("        top: 70px;\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        text-align: left;\n");
      out.write("        right: 0px;\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #login-table {\n");
      out.write("        margin: 20px 12px;\n");
      out.write("    }\n");
      out.write("    #login-menu input {\n");
      out.write("        width: 200px;\n");
      out.write("        height: 40px;\n");
      out.write("        padding: 10px;\n");
      out.write("        text-align: left;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        margin: 2px auto;\n");
      out.write("    }\n");
      out.write("    #login-menu button {\n");
      out.write("        width: 200px;\n");
      out.write("        height: 40px;\n");
      out.write("        margin: 2px auto;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        background-color: dodgerblue;\n");
      out.write("        border: 0px;\n");
      out.write("        font-weight: 900;\n");
      out.write("        color: #fff;\n");
      out.write("        font-size: 15px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 여기까지 틀잡기 */\n");
      out.write("\n");
      out.write("    #menubarNav ul>li {\n");
      out.write("        width: 20%;\n");
      out.write("        float: left;\n");
      out.write("        list-style-type: none;\n");
      out.write("        margin: 0 15px;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("    #menubarNav ul a {\n");
      out.write("        color : white;\n");
      out.write("        font-size: 16px;\n");
      out.write("    }\n");
      out.write("    #menubarNav ul a:hover {\n");
      out.write("        color : yellowgreen;\n");
      out.write("        text-decoration: none;\n");
      out.write("    }\n");
      out.write("    header ul {\n");
      out.write("    \tlist-style-type: none;\n");
      out.write("    }\n");
      out.write("    #mypageMenu ul>li>a {\n");
      out.write("    \ttext-decoration:none;\n");
      out.write("    \tfont-size:20px;\n");
      out.write("    }\n");
      out.write("    #compareMenu {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 600px;\n");
      out.write("        background-color: rgba(0,38,75,0.8);\n");
      out.write("        text-align: center;\n");
      out.write("        display: none; \n");
      out.write("        float: left;\n");
      out.write("        z-index: 1000;\n");
      out.write("    }\n");
      out.write("    #compareMenu * {\n");
      out.write("        /* border: 1px solid white; */\n");
      out.write("        display: inline-block;\n");
      out.write("    }\n");
      out.write("    .comWrapper {\n");
      out.write("        width: 900px;\n");
      out.write("        height: 500px;\n");
      out.write("        margin: 0 auto;\n");
      out.write("        text-align: center;\n");
      out.write("        position: relative;\n");
      out.write("    }\n");
      out.write("    .comWrapper i, .comStart {\n");
      out.write("        cursor: pointer;\n");
      out.write("        line-height: 500px;\n");
      out.write("        font-size: 100px;\n");
      out.write("        color: rgba(255, 255, 255, 0.7);\n");
      out.write("    }\n");
      out.write("    .comDevice1, .comDevice2 {\n");
      out.write("        width: 400px;\n");
      out.write("        height: 100%;\n");
      out.write("        position: absolute;\n");
      out.write("        top: 0;\n");
      out.write("    }\n");
      out.write("    .comDevice1 {\n");
      out.write("        left: 0;\n");
      out.write("    }\n");
      out.write("    .comDevice2 {\n");
      out.write("        right: 0;\n");
      out.write("    }\n");
      out.write("    .comStart {\n");
      out.write("        width: 90px;\n");
      out.write("        height: 100%;\n");
      out.write("    }\n");
      out.write("    .loginmenu {\n");
      out.write("        z-index: 10;\n");
      out.write("    }\n");
      out.write("    #veil {\n");
      out.write("        display: none;\n");
      out.write("        z-index: 5;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        position: fixed;\n");
      out.write("        top: 0;\n");
      out.write("        left: 0;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("    $(document).ready(function(){\n");
      out.write("        $(\"#account\").click(function(){\n");
      out.write("        \t$(\".loginmenu\").toggle();\n");
      out.write("        });\n");
      out.write("        $(\"#veil\").on(\"click\", function(){\n");
      out.write("        \t$(\".loginmenu\").toggle();\n");
      out.write("        });\n");
      out.write("        $(\"#compareOpen\").click(function(){\n");
      out.write("            // $(\".compareMenu\").slideToggle(500);\n");
      out.write("            $(\".compareMenu\").css(\"display\", \"block\");\n");
      out.write("        });\n");
      out.write("        $(\"#adminPage\").click(function(){\n");
      out.write("        \tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/loadAdminMain.do\";\n");
      out.write("        });\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header class=\"navbar sticky-top navbar-expand navbar-dark flex-column flex-md-row bd-navbar\">\n");
      out.write("        <section id=\"logo\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("'\">SPEC</section>\n");
      out.write("        <div id=\"menubarNav\" class=\"navbar-nav-scroll\">\n");
      out.write("            <ul class=\"navbar-nav bd-navbar-nav flex-row\" >\n");
      out.write("                <li class=\"nav-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/devicelist.mo\">MOBILE</a></li>\n");
      out.write("                ");
      out.write("\n");
      out.write("                <li class=\"nav-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/calendar.do\">CALENDAR</a></li>\n");
      out.write("                <li class=\"nav-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?bno=0\">COMMUNITY</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- <section id=\"blank\"></section> -->\n");
      out.write("        <ul id=\"login\" class=\"navbar-nav flex-row ml-md-auto d-none d-md-flex\">\n");
      out.write("             ");
 if( loginUser != null && loginUser.getUserStatus() == 0) {
      out.write("\n");
      out.write("            <li><i id=\"adminPage\" class=\"material-icons\">settings</i></li>\n");
      out.write("            \t");
 } 
      out.write(" \n");
      out.write("            <li class=\" nav-item dropdown\">\n");
      out.write("            \n");
      out.write("                <i class=\"material-icons\" id=\"account\">account_circle</i>\n");
      out.write("                <div class=\"loginmenu\" id=\"veil\"></div>\n");
      out.write("            \t");
 if(loginUser == null){ 
      out.write("\n");
      out.write("        <div id=\"login-menu\" class=\" dropdown-menu-right loginmenu\" aria-labelledby=\"account\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\">\n");
      out.write("            \t<table id=\"login-table\">\n");
      out.write("\t                <tr>\n");
      out.write("\t                    <td><input type=\"text\" name=\"userEmail\" id=\"user-email\" placeholder=\"이메일 주소\" autocomplete=\"off\"></td>\n");
      out.write("\t                </tr>\n");
      out.write("\t                <tr>\n");
      out.write("\t                    <td><input type=\"password\" name=\"userPwd\" id=\"user-pwd\" placeholder=\"비밀번호\"></td>\n");
      out.write("\t                </tr>\n");
      out.write("\t                <tr>\n");
      out.write("\t                    <td><button type=\"submit\">L O G I N</button></td>\n");
      out.write("\t                </tr>\n");
      out.write("\t                <tr>\n");
      out.write("\t                    <td class=\"taright gray\"><a href=\"inputNameForm.me\" class=\"gray\">아이디</a> / <a href=\"inputEmailForm.me\" class=\"gray\">비밀번호</a> 찾기</td>\n");
      out.write("\t                </tr>\n");
      out.write("\t                <tr>\n");
      out.write("\t                    <td><br>회원이 아니신가요?<br> <a href=\"joinForm.me\"><p class=\"emp blue\">가입하기</p></a>\n");
      out.write("\t                    </td> \n");
      out.write("\t                </tr>\n");
      out.write("            \t</table>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        ");
 } else{ 
      out.write("\n");
      out.write("        <div id=\"mypageMenu\" class=\"dropdown-menu dropdown-menu-right loginmenu\" aria-labelledby=\"account\">\n");
      out.write("        \t<ul>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage.me\">회원정보</a></li>\n");
      out.write("        \t\t<li><a href=\"inputPwdForm.me?code=1\">정보수정</a></li>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myBoardList.me\">내글관리</a></li>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myReviewList.me\">내리뷰관리</a></li>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myReplyList.me\">내댓글관리</a></li>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myReportList.me\">신고내역보기</a></li>\n");
      out.write("        \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\">로그아웃</a></li>\n");
      out.write("        \t</ul>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("    \n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </header>\n");
      out.write("    <div class=\"compareMenu\" id=\"compareMenu\">\n");
      out.write("        <form>\n");
      out.write("           <div class=\"comWrapper\">\n");
      out.write("               <div class=\"comDevice1\"><i class=\"material-icons\">add_circle</i></div>\n");
      out.write("               <div class=\"comStart\">VS</div>\n");
      out.write("               <div class=\"comDevice2\"><i class=\"material-icons\">add_circle</i></div>\n");
      out.write("           </div>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </div>\t\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<nav id=\"bnav\"> \r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BoardList Nav</title>\r\n");
      out.write(" \t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write(" \t<style>\r\n");
      out.write("\t\t #boardnav{\r\n");
      out.write("\t\t \twidth: 1080px;\r\n");
      out.write("\t\t\theight: 140px;\r\n");
      out.write("\t\t\tmargin: auto;\r\n");
      out.write("\t\t\tpadding: 0;\r\n");
      out.write("\t\t\tclear : both; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#boardnav> #menu > div{ \r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            color: #00264B;\r\n");
      out.write("            display:block;\r\n");
      out.write("            float:left;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("          \t/* border: 1px solid black; */\r\n");
      out.write("          \t\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #menu > div:hover{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: rgb(53, 12, 236);\r\n");
      out.write("        }\r\n");
      out.write("        #menu{\r\n");
      out.write("       /*  padding-top:30px; */\r\n");
      out.write("       margin-top: 35px;\r\n");
      out.write("       margin-left:70px;\r\n");
      out.write("       padding:0;\r\n");
      out.write("       padding-botton:5px;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav id=\"boardnav\">\r\n");
      out.write("\t\t<article id=\"menu\">\r\n");
      out.write("\t    \t<div id=\"total\" onclick=\"goBoard(0);\">전체 게시판</div>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t        <div id=\"lg\" onclick=\"goBoard(1);\">LG게시판</div>\r\n");
      out.write("\t       \r\n");
      out.write("\t        <div id=\"samsung\" onclick=\"goBoard(2);\">삼성게시판</div>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <div id=\"apple\" onclick=\"goBoard(3);\">Apple게시판</div>\r\n");
      out.write("\t      \r\n");
      out.write("\t        <div id=\"etc\" onclick=\"goBoard(4);\">타브랜드게시판</div>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <div id=\"free\" onclick=\"goBoard(5);\">자유게시판</div>\r\n");
      out.write("\t        \r\n");
      out.write("\t    </article>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <script>\r\n");
      out.write("    \tfunction goBoard(num){\r\n");
      out.write("    \t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?bno=\"+num;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t/* $(function(){\r\n");
      out.write("    \t\t$(\"#menu div\").click(function(){\r\n");
      out.write("    \t\t\t$(this).css({\"background-color\": \"#00264B\", \"color\" : \"white\"});\r\n");
      out.write("    \t\t}).mouseout(function(){\r\n");
      out.write("    \t\t\t$(this).css({\"background-color\": \"#00264B\", \"color\" : \"white\"});\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}); */\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\tswitch(");
      out.print(request.getAttribute("bno"));
      out.write("){\r\n");
      out.write("\t\t\tcase 0 : $(\"#total\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\tcase 1: $(\"#lg\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\tcase 2: $(\"#samsung\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\tcase 3: $(\"#apple\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\tcase 4: $(\"#etc\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\tcase 5: $(\"#free\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"}); break;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("    <section id=\"ad\">\r\n");
      out.write("     <article id=\"ad-2\">AD</article>\r\n");
      out.write("   \t</section>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<section id=\"blist\">\r\n");
      out.write("   \t\t<section id=\"boardlist\">\r\n");
      out.write("\t      \t<table class=\"table table-hover\" id=\"boardlisttable\">\r\n");
      out.write("\t        \t<thead>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t                    <th scope=\"col\" width=\"10%\">번호</th>\r\n");
      out.write("\t                    <th scope=\"col\" width=\"10%\">분류</th>\r\n");
      out.write("\t                    <th scope=\"col\" width=\"55%\">제목</th>\r\n");
      out.write("\t                    <th scope=\"col\" width=\"15%\">날짜</th>\r\n");
      out.write("\t                    <th scope=\"col\" width=\"10%\">조회</th>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t            </thead>\r\n");
      out.write("\t            <tbody>\r\n");
      out.write("\t            \t");
 if(tlist.isEmpty()){ 
      out.write("\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td colspan=\"5\"> 등록된 게시글이 없습니다.</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t");
 }else{ 
      out.write("\r\n");
      out.write("\t            \t\t");
for(Board b : tlist){ 
      out.write("\r\n");
      out.write("\t            \t\t<tr>\r\n");
      out.write("\t            \t\t\t<td>");
      out.print( b.getbNo());
      out.write("</td>\r\n");
      out.write("\t            \t\t\t<td>");
      out.print( b.getCgCategory());
      out.write("</td>\r\n");
      out.write("\t            \t\t\t<td>");
      out.print( b.getbTitle());
      out.write("</td>\r\n");
      out.write("\t            \t\t\t<td>");
      out.print( b.getbRegdate());
      out.write("</td>\r\n");
      out.write("\t            \t\t\t<td>");
      out.print( b.getbCount());
      out.write("</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t");
 } 
      out.write("\r\n");
      out.write("\t            \t");
 } 
      out.write("\r\n");
      out.write("\t            </tbody>   \r\n");
      out.write("\t       \t</table>\r\n");
      out.write("\t   \t</section>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <section id=\"boardbtn\">\r\n");
      out.write("\t       \t<button type=\"button\" class=\"btn btn-secondary\"style=\"background-color : white; color : black; display : block; font-weight:bold; float : left; margin: 0 10px 0 5px;\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?bno=");
      out.print(request.getAttribute("bno"));
      out.write("'\">목록</button>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <form class=\"form-inline my-2 my-lg-0\" action=\"");
      out.print(request.getContextPath() );
      out.write("/boardSearch.bo\" method=\"GET\">\r\n");
      out.write("\t\t        <input class=\"form-control mr-sm-2\" type=\"text\" name=\"text\" placeholder=\"Search\">\r\n");
      out.write("\t\t        <input type=\"hidden\" name=\"bno\" value=\"");
      out.print(request.getAttribute("bno"));
      out.write("\">\r\n");
      out.write("\t\t        <button type=\"submit\" class=\"btn btn-secondary\"style=\"background-color : white; color : black; font-weight:bold; margin:0;\">검색</button>\r\n");
      out.write("\t\t      \t<select name=\"search\" id=\"searchselect\">\r\n");
      out.write("\t\t\t\t\t<option value=\"title\" selected>제목</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"titleContent\">제목 + 내용</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"content\">내용</option>\r\n");
      out.write("\t\t\t\t<!-- \t<option value=\"head\">말머리</option> -->\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(loginUser != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"style=\"background-color : white; color : black; display : block; font-weight:bold; float : right; margin: 0 10px 0 5px;\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/writeform.bo'\">글쓰기</button>\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!-- 페이징바 -->\r\n");
      out.write("\t    <section id=\"boardpage\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t         <ul class=\"pagination pagination-sm\">\r\n");
      out.write("\t\t   \t\t\t<!-- 맨 처음(<<) -->\r\n");
      out.write("\t\t   \t\t\t<li class=\"page-item \">\r\n");
      out.write("\t\t   \t\t\t\t<a class=\"page-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/maintotal.bo?currentPage=1&bno=");
      out.print(request.getAttribute("bno"));
      out.write("\">&laquo;</a>\r\n");
      out.write("\t\t   \t\t\t</li>\r\n");
      out.write("\t\t   \t\t\t<!-- 이전 페이지로 -->\r\n");
      out.write("\t\t   \t\t\t");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t   \t\t\t\t<a class=\"page-link\">&lt;</a>\r\n");
      out.write("\t\t\t   \t\t\t</li>\r\n");
      out.write("\t\t   \t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t   \t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?currentPage=");
      out.print( currentPage-1 );
      out.write("&bno=");
      out.print(request.getAttribute("bno"));
      out.write("\">&lt;</a>\r\n");
      out.write("\t\t\t   \t\t\t</li>\r\n");
      out.write("\t\t   \t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t   \t\t\t<!-- 페이지 목록 넘기기 -->\r\n");
      out.write("\t\t   \t\t\t");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t   \t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t   \t\t\t\t\t<a class=\"page-link\">");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t   \t\t\t\t</li>\r\n");
      out.write("\t\t\t   \t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t   \t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t   \t\t\t\t<a class=\"page-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/maintotal.bo?currentPage=");
      out.print( p);
      out.write("&bno=");
      out.print(request.getAttribute("bno"));
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t\t   \t\t\t</li>\r\n");
      out.write("\t\t\t   \t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t   \t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t     \t\t\r\n");
      out.write("\t\t     \t\t<!-- 다음 페이지로 -->\r\n");
      out.write("\t\t     \t\t");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t   \t\t\t\t<a class=\"page-link\">&gt;</a>\r\n");
      out.write("\t\t\t   \t\t\t</li>\r\n");
      out.write("\t\t   \t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t   \t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?currentPage=");
      out.print( currentPage+1 );
      out.write("&bno=");
      out.print(request.getAttribute("bno"));
      out.write("\">&gt;</a>\r\n");
      out.write("\t\t\t   \t\t\t</li>\r\n");
      out.write("\t\t   \t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t     \t\t<!-- 맨끝으로(>>) -->\r\n");
      out.write("\t\t    \t\t <li class=\"page-item\">\r\n");
      out.write("\t\t     \t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/maintotal.bo?currentPage=");
      out.print( maxPage );
      out.write("&bno=");
      out.print(request.getAttribute("bno"));
      out.write("\">&raquo;</a>\r\n");
      out.write("\t\t     \t\t</li>\r\n");
      out.write("\t   \t\t\t</ul>\r\n");
      out.write("\t   \t\t</div> \r\n");
      out.write("\t  \t</section>\r\n");
      out.write("   \t</section>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("    <!-- <script>\r\n");
      out.write("    \t$(document).ready(function(){\r\n");
      out.write("    \t\t$(\"#total\").css({\"background-color\": \"#00264B\", \"color\" : \"white\"});\r\n");
      out.write("    \t}); \r\n");
      out.write("    \r\n");
      out.write("    </script> -->\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \t// 게시판 상세보기\r\n");
      out.write("    \t$(function(){ \r\n");
      out.write("    \t\t$(\"#boardlisttable td\").click(function(){\r\n");
      out.write("    \t\t\tvar bcode = ");
      out.print(request.getAttribute("bno"));
      out.write(";\r\n");
      out.write("    \t\t\tvar bno = $(this).parent().children().eq(0).text();\r\n");
      out.write("    \t\t\t");
if(loginUser !=null){
      out.write("\t\r\n");
      out.write("    \t\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/content.bo?bno=\"+bno +\"&bcode=\"+ bcode;\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\talert(\"로그인해야만 상세보기가 가능합니다!\");\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
